# Generated by Django 6.0.4 on 2026-04-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_book_genre_remove_book_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='borrowed', max_length=20),
        ),
    ]
